Remove keyword argument to getattr
getattr doesn't support keyword arguments for recent python versions at least.

```
for p in 3.10 3.11 3.12 3.13 3.14; do echo "Python $p"; uv run --python $p test.py; echo; done

Python 3.10
Traceback (most recent call last):
  File "/home/kunalb/rough/2025/06/20/test.py", line 1, in <module>
    getattr(1, 'a', default=None)
TypeError: getattr() takes no keyword arguments

Python 3.11
Traceback (most recent call last):
  File "/home/kunalb/rough/2025/06/20/test.py", line 1, in <module>
    getattr(1, 'a', default=None)
TypeError: getattr() takes no keyword arguments

Python 3.12
Traceback (most recent call last):
  File "/home/kunalb/rough/2025/06/20/test.py", line 1, in <module>
    getattr(1, 'a', default=None)
TypeError: getattr() takes no keyword arguments

Python 3.13
Traceback (most recent call last):
  File "/home/kunalb/rough/2025/06/20/test.py", line 1, in <module>
    getattr(1, 'a', default=None)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: getattr() takes no keyword arguments

Python 3.14
Traceback (most recent call last):
  File "/home/kunalb/rough/2025/06/20/test.py", line 1, in <module>
    getattr(1, 'a', default=None)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: getattr() takes no keyword arguments
```